template: home

categories:
  - name: 常用网站
    sites:
      - name: 必应
        description: 中文搜索引擎
        remark: 必应
        url: www.bing.com/
      - name: 谷歌
        description: 国际搜索引擎
        url: https://www.google.com/
      - name: 哔哩哔哩
        description: 知名视频社区
        url: https://www.bilibili.com/
      - name: cs自学指南
        description: cs自学指南
        url: https://csdiy.wiki/
  - name: 开发技术
    sites:
      - name: GitHub
        description: 全球最大的软件开发平台
        url: https://github.com/
      - name: Stack Overflow
        description: 程序员问答社区
        url: https://stackoverflow.com/
      - name: Node Seek
        description: Node Seek
        url: https://www.nodeseek.com/
      - name: Linux Do
        description: Linux Do
        url: https://linux.do/
      - name: Docker镜像监控
        description: Docker镜像监控
        url: https://status.anye.xyz/
      - name: V2EX
        description: 创意工作者社区
        url: https://www.v2ex.com/
  - name: 脚本
    sites:
      - name: linux一键换源
        description: linux一键换源
        url: https://linuxmirrors.cn/

  - name: 效率工具
    sites:
      - name: 在线工具箱
        description: 各种便捷在线小工具合集
        url: https://tool.lu/
      - name: Notion
        description: 笔记、知识库与任务管理工具
        url: https://www.notion.so/
  - name: 娱乐
    sites:
      - name: Behance
        description: 创意人士作品集展示平台
        url: https://www.behance.net/
      - name: Unsplash
        description: 免费高质量图片素材库
        url: https://unsplash.com/
